# Generated by Django 4.1.7 on 2023-07-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_product_short_description_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='url_title',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True, verbose_name='توضیحات مختصر'),
        ),
    ]
