# Generated by Django 4.1.7 on 2023-07-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_productcategory_url_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
