# Generated by Django 4.1.7 on 2023-07-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_producttype_productcategory_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.ImageField(null=True, upload_to='types/', verbose_name='عکس'),
        ),
    ]
