# Generated by Django 4.1.7 on 2023-07-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_producttype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.ManyToManyField(null=True, to='product_module.productcategory'),
        ),
    ]
