# Generated by Django 4.1.7 on 2023-07-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_alter_producttype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='category',
        ),
    ]
