# Generated by Django 4.1.7 on 2023-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_remove_producttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.ManyToManyField(to='product_module.productcategory'),
        ),
    ]
