# Generated by Django 4.1.7 on 2023-07-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_producttype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='group',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='group',
            field=models.ManyToManyField(to='product_module.producttype', verbose_name='نوع'),
        ),
    ]
