# Generated by Django 4.1.7 on 2023-07-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0018_remove_productcategory_group_productcategory_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='group',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.producttype', verbose_name='نوع محصول'),
        ),
    ]
