# Generated by Django 4.1.7 on 2023-07-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_remove_productcategory_group_productcategory_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='category',
        ),
    ]
