# Generated by Django 4.1.7 on 2023-07-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0020_remove_producttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='url_title',
            field=models.SlugField(max_length=300, null=True, verbose_name='عنوان در url'),
        ),
    ]
