# Generated by Django 4.1.7 on 2023-07-22 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_module', '0011_producttype_image'),
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['final_price'], 'verbose_name': 'جزعیات رسید', 'verbose_name_plural': 'جزعیات رسید ها'},
        ),
        migrations.AddField(
            model_name='order',
            name='date_of_payment',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(null=True, verbose_name='پرداخت شده / نشده'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(null=True, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='final_price',
            field=models.IntegerField(null=True, verbose_name='قیمت نهایی'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_module.order', verbose_name='رسید'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول'),
        ),
    ]
