# Generated by Django 4.1.7 on 2023-07-30 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_module', '0002_alter_order_options_alter_orderdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['final_price'], 'verbose_name': 'جزعیات سبد خرید', 'verbose_name_plural': 'لیست جزعیات سبد خرید'},
        ),
        migrations.CreateModel(
            name='OrderCheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='نام')),
                ('last_name', models.CharField(max_length=300, verbose_name='نام خانوادگی')),
                ('company', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام شرکت')),
                ('country', models.CharField(max_length=200, verbose_name='کشور | منطقه')),
                ('state', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('street_address', models.TextField(verbose_name='ادرس خیابان')),
                ('more_complete_address', models.TextField(blank=True, null=True, verbose_name='آپارتمان، مجتمع، واحد و... ')),
                ('postal_code', models.IntegerField(verbose_name='کد پستی')),
                ('phone', models.IntegerField(verbose_name='تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_module.order', verbose_name='رسید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جزعیات نهایی سفارش',
                'verbose_name_plural': 'لیست جزعیات نهایی سفارش ها',
                'db_table': 'ordercheckouts',
            },
        ),
    ]
