# Generated by Django 4.1.7 on 2023-07-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_alter_ordercheckout_city_alter_ordercheckout_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transportation',
            field=models.BooleanField(null=True, verbose_name='حمل نقل رایگان / پولی'),
        ),
    ]
