# Generated by Django 4.1.7 on 2023-08-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_order_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت حمل و نقل'),
        ),
    ]
