# Generated by Django 4.1.7 on 2023-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_order_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(default=0, null=True, verbose_name='تعداد'),
        ),
    ]
