# Generated by Django 4.1.7 on 2023-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان اسلاید')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='عکس اسلاید')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلاید ها',
            },
        ),
    ]
