# Generated by Django 4.1.7 on 2023-07-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_questionanswer_alter_sitebanner_position_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(null=True, verbose_name='جواب'),
        ),
    ]
