# Generated by Django 4.1.7 on 2023-07-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_questionanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='product_count',
            field=models.IntegerField(blank=True, editable=False, verbose_name='تعداد کل محصولات'),
        ),
    ]
