# Generated by Django 4.1.7 on 2023-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_alter_sitesetting_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/', verbose_name='لوگو سایت'),
        ),
    ]
