# Generated by Django 4.1.7 on 2023-07-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_sitesetting_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
