# Generated by Django 4.1.7 on 2023-07-13 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_module', '0009_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدید ها'},
        ),
        migrations.AddField(
            model_name='visit',
            name='ip',
            field=models.CharField(max_length=300, null=True, verbose_name='ای پی'),
        ),
        migrations.AddField(
            model_name='visit',
            name='product_or_blog',
            field=models.CharField(choices=[('product_detail', 'تعداد بازدید محصولات'), ('blog_detail', 'تعداد بازدید وبلاگ')], max_length=300, null=True, verbose_name='محصول یا بلاگ'),
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
