# Generated by Django 4.1.7 on 2023-07-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0006_alter_blogcategory_url_title'),
        ('product_module', '0011_producttype_image'),
        ('site_module', '0011_visit_is_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='blog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_module.blogcategory', verbose_name='بلاگ'),
        ),
        migrations.AddField(
            model_name='visit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول'),
        ),
    ]
