# Generated by Django 4.1.7 on 2023-07-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0013_alter_visit_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='blog_category',
            new_name='blog',
        ),
    ]
