# Generated by Django 4.1.7 on 2023-07-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل کاربر')),
                ('Issue', models.CharField(max_length=50, verbose_name='موضوع پیام')),
                ('message_text', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیام ارسالی',
                'verbose_name_plural': 'پیام های ارسالی',
            },
        ),
    ]
