# Generated by Django 4.1.7 on 2023-07-11 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_module', '0011_producttype_image'),
        ('blog_module', '0006_alter_blogcategory_url_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='دیدگاه کاربر')),
                ('commentposition', models.CharField(choices=[('main_page', 'صفحه اصلی'), ('product_detail', 'صفحه جزعیات محصولات'), ('blog_detail', 'صفحه جزعیات وبلاگ')], max_length=300, verbose_name='محل و موقعیت کامنت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد کامنت')),
                ('read_by_admin', models.BooleanField(default=True, verbose_name='خوانده شده توسط ادمین یا خیر')),
                ('is_accepted', models.BooleanField(default=False, null=True, verbose_name='تایید شده یا خیر')),
                ('is_subcomment', models.BooleanField(default=False, null=True, verbose_name='پاسخ است یا خیر')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_module.blog', verbose_name='بلاگ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
