# Generated by Django 4.1.7 on 2023-07-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='full_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='کاربر'),
        ),
    ]
