# Generated by Django 4.1.7 on 2023-07-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_module', '0002_remove_comment_user_comment_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_star',
            field=models.BooleanField(null=True, verbose_name='ستاره دار است یا خیر'),
        ),
    ]
