# Generated by Django 4.1.7 on 2023-07-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_module', '0004_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.IntegerField(null=True, verbose_name='تعداد ستاره / امتیاز'),
        ),
    ]
