# Generated by Django 4.1.7 on 2023-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='url_title',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='عنوان در url'),
        ),
    ]
