# Generated by Django 4.1.7 on 2023-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0005_blogcategory_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='url_title',
            field=models.SlugField(max_length=300, null=True, verbose_name='عنوان در url'),
        ),
    ]
