# Generated by Django 4.1.7 on 2023-07-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.CharField(choices=[('admin', 'مدیر عامل'), ('programmer', 'برنامه نویس'), ('graphic_designer', 'طراح گرافیک'), ('SEO', 'سئو')], max_length=300, null=True, verbose_name='گروه'),
        ),
    ]
